// @ts-check
import eslint from "@eslint/js";
import importX from "eslint-plugin-import-x";
import jest from "eslint-plugin-jest";
import jestExtended from "eslint-plugin-jest-extended";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";
import yml from "eslint-plugin-yml";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      // This file.
      "eslint.config.mjs",
      // Jest config files — not part of the typed TS project.
      "**/jest.config.js",
      // Any build output
      "**/dist",
      // Ambient type declarations
      "**/*.d.ts",
      // Generated lockfile — pnpm-managed, not ours to lint/format.
      "**/pnpm-lock.yaml",
      // Workspace yaml — pnpm-managed (writes single-quoted entries when
      // accepting the supply-chain prompt), not ours to lint/format.
      "**/pnpm-workspace.yaml",
      // TypeORM migration files — generated by the typeorm CLI from a
      // separate tsconfig (`apps/bertie/typeorm/tsconfig.json`) and not
      // part of the root TS project service.
      "**/typeorm/migrations/**",
    ],
  },
  eslint.configs.recommended,
  tseslint.configs.recommended,
  eslintPluginPrettierRecommended,
  {
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.jest,
      },
      sourceType: "commonjs",
      parserOptions: {
        projectService: true,
        // Anchor project resolution to this config's directory. Without this,
        // typescript-eslint's project service fails when a single eslint
        // invocation receives files from multiple candidate roots — notably
        // `packages/*` (uses this config) plus `apps/bertie` (uses its own
        // `eslint.config.mjs`). Each config must anchor its own root.
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    files: ["**/*.ts"],
    plugins: {
      "import-x": importX,
    },
    rules: {
      "@typescript-eslint/no-unsafe-argument": "error",
      // Don't use semi-colons to terminate statements.
      semi: ["error", "never"],
      // Force explicitly stated return types to avoid errors where a function returns 2 different types.
      "@typescript-eslint/explicit-function-return-type": "error",
      // Force public, private, protected to be explicitly stated.
      "@typescript-eslint/explicit-member-accessibility": "error",
      // Ensure promises are handled.
      "@typescript-eslint/no-floating-promises": "error",
      // Allow explicit anys as they are often used in request code e.g. when fetching headers.
      "@typescript-eslint/no-explicit-any": "off",
      // Any prettier issues are a lint error.
      "prettier/prettier": ["error"],
      // Prefer `import { type Foo }` syntax — enables tree-shaking and makes type-vs-value intent explicit.
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      // Catch passing async functions where a void callback is expected (common NestJS footgun with event handlers).
      "@typescript-eslint/no-misused-promises": "error",
      // Force handling all union/enum cases in switch — prevents silent bugs when a discriminated union grows.
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      // Ensure `return await` inside try/catch so the async stack trace is preserved.
      "@typescript-eslint/return-await": ["error", "in-try-catch"],
      // Prefer `??` over `||` to avoid falsy-value bugs with `0`, `""`, `false`.
      "@typescript-eslint/prefer-nullish-coalescing": "error",
      // Prefer `a?.b` over `a && a.b` — cleaner and less error-prone.
      "@typescript-eslint/prefer-optional-chain": "error",
      // Barrel-only export tree (#28): historically forbade deep subpath
      // imports via `@neomaventures/request-context/*`. request-context now
      // ships a legitimate `/testing` subpath, so the restriction is lifted.
      // Any future package-internal subpath restrictions live in that
      // package's own eslint override.
      "no-restricted-imports": ["error", { patterns: [] }],
      // Import sorting and organization.
      "import-x/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          "newlines-between": "always",
          alphabetize: { order: "asc" },
        },
      ],
      // Detect circular dependencies.
      "import-x/no-cycle": "error",
      // Prevent duplicate imports. prefer-inline pairs with consistent-type-imports to inline type specifiers.
      "import-x/no-duplicates": ["error", { "prefer-inline": true }],
    },
  },
  // Jest — enforces spec-file best practices (no .only, no conditional expect,
  // valid describe/expect, etc.) via the plugin's recommended preset. Scoped to
  // spec files only; source files are untouched.
  {
    files: ["**/*.spec.ts", "**/*.e2e-spec.ts"],
    ...jest.configs["flat/recommended"],
    plugins: {
      ...jest.configs["flat/recommended"].plugins,
      ...jestExtended.configs["flat/all"].plugins,
    },
    rules: {
      ...jest.configs["flat/recommended"].rules,
      // jest-extended matchers are loaded pack-wide via `jest-extended/all`;
      // the companion plugin's `flat/all` preset enables all 5 rules that
      // push specs toward `toBeTrue`, `toBeFalse`, `toBeArray`, `toBeObject`,
      // and `toHaveBeenCalledOnce`. All 5 rules are autofixable, so the
      // sweep is mechanical. Pre-existing residuals (if any) disabled with
      // TODO(jest-extended#330) markers for per-package follow-up.
      ...jestExtended.configs["flat/all"].rules,
      // Recognise supertest's chained `.expect(...)` as an assertion so e2e
      // specs that end in `request(app).get(...).expect(200)` don't trip the
      // rule. Default `expect` covers jest's global.
      "jest/expect-expect": [
        "warn",
        { assertFunctionNames: ["expect", "request.**.expect"] },
      ],
      // Allow `describe(variableOrConstant, ...)` — several specs derive the
      // describe title from a `LOCATION` const or iterate parameterised
      // fixtures via `.forEach(({ title }) => describe(title, ...))`. The
      // string-type check on it/test titles stays on.
      "jest/valid-title": ["error", { ignoreTypeOfDescribeName: true }],
      // Allow `expect(...)` inside `beforeEach` / `afterEach` / `beforeAll` /
      // `afterAll` as a pre-/post-condition assertion. Real-infra e2e specs
      // often boot fixtures whose behaviour IS the setup contract — asserting
      // that in the hook keeps the `it` body focused on the actual claim
      // under test. A failed pre-condition points at the hook, not a test
      // that never ran. `expect` outside any of these blocks still errors.
      "jest/no-standalone-expect": [
        "error",
        {
          additionalTestBlockFunctions: [
            "beforeEach",
            "afterEach",
            "beforeAll",
            "afterAll",
          ],
        },
      ],
      // Allow the `done` callback style. Sync-signature-with-callback shapes
      // (Nest middleware `use(req, res, next)`) read more naturally with
      // `done` than with `await new Promise((resolve) => ...)`. Jest itself
      // still errors within a single test if you mix `async` and `done`, so
      // per-test correctness is guaranteed.
      "jest/no-done-callback": "off",
    },
  },
  // YAML — parses + validates .yml/.yaml (workflows, pnpm-workspace) so a
  // malformed file fails `pnpm lint` locally, before it's pushed. `flat/prettier`
  // defers formatting to prettier (which already runs via the plugin above).
  ...yml.configs["flat/recommended"],
  ...yml.configs["flat/prettier"],
);
